name: Backstage Catalog Software and TechDocs
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  workflow:
    # See more about workflow in this doc https://github.com/will-bank/backstage-catalog-software-and-techdocs-workflow#readme
    uses: will-bank/backstage-catalog-software-and-techdocs-workflow/.github/workflows/backstage-catalog-software-and-techdocs.yml@main     
    secrets:
      PLATFORMS_TOKEN: ${{ secrets.WILLBANK_PLATFORMS_PERSONAL_ACCESS_TOKEN }}
