name: Build Deploy Kubernetes Application
run-name: Build Deploy Kubernetes Application in [${{ inputs.ENVIRONMENT }}] by ${{ github.actor }} ${{ github.run_number }}

# Before running this workflow checkout its prerequisites at:
# https://github.com/will-bank/build-deploy-kubernetes-application-workflow#readme

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        description: 'Environment to run pipeline'
        required: true
        default: development
        options:
          - development
          - staging
          - production

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  workflow:
    uses: will-bank/build-deploy-kubernetes-application-workflow/.github/workflows/build-deploy-kubernetes-application.yml@v0.3.0  
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      # BUILD_ARGS: |
      #   --build-arg ENVIRONMENT=${{ inputs.ENVIRONMENT }}
    secrets:
      PLATFORMS_TOKEN: ${{ secrets.WILLBANK_PLATFORMS_PERSONAL_ACCESS_TOKEN }}
