name: Build Deploy MFE Evoluwill Application
run-name: Build Deploy MFE Evoluwill Application in [${{ inputs.ENVIRONMENT }}] by ${{ github.actor }} ${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        description: 'Environment to run pipeline'
        required: true
        default: development
        options:
          - development
          - production
      APP_NAME:
        type: string
        description: 'Application name to deploy'
        required: true
      NODE_VERSION:
        type: choice
        description: 'Environment to run pipeline'
        required: true
        default: "16"
        options:
          - "16"
          - "18"

permissions:
  id-token: write
  contents: write
  actions: write

env:
  GPR_TOKEN: ${{ secrets.WILLBANK_PLATFORMS_GPR_TOKEN }}
jobs:
  setup_build_deploy:
    name: Install Test and Build
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}
    strategy:
      matrix:
        node-version: ["${{ inputs.NODE_VERSION }}"]
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Setup environment vars
        run: |
          if [ ${{ inputs.ENVIRONMENT }} == "production" ]; then
            echo "BUCKET_S3=${{ vars.PROD_BUCKET_S3_EVOLUWILL_MFE }}" >> $GITHUB_ENV
            echo "ASSUME_ROLE=${{ vars.PROD_ROLE_EVOLUWILL_MFE }}" >> $GITHUB_ENV
            echo "CLOUDFRONT_ID=${{ vars.PROD_CLOUDFRONT_ID_EVOLUWILL_MFE }}" >> $GITHUB_ENV
            
          else
            echo "BUCKET_S3=${{ vars.DEV_BUCKET_S3_EVOLUWILL_MFE }}" >> $GITHUB_ENV
            echo "ASSUME_ROLE=${{ vars.DEV_ROLE_EVOLUWILL_MFE }}" >> $GITHUB_ENV
            echo "CLOUDFRONT_ID=${{ vars.DEV_CLOUDFRONT_ID_EVOLUWILL_MFE }}" >> $GITHUB_ENV
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.ASSUME_ROLE }}
          role-session-name: githubActions
          aws-region: ${{ vars[format('development_{0}', 'AWS_REGION')] }}

      - name: Use Node.js ${{ inputs.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.NODE_VERSION }}

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install

      - name: Create .env file
        run: |
          echo "$ENV_CONTENT" > .env
        env:
          ENV_CONTENT: ${{ secrets.ENV_FILE }}

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Run Tests
        run: pnpm test:coverage

      - name: Check coverage
        run: ./scripts/mfe-evoluwill-check-coverage.sh

      - name: Deploy Project
        run: |
          aws s3 sync ./dist s3://${env.BUCKET_S3}/evoluwill-mfe-${{ inputs.APP_NAME }} --delete
          aws cloudfront create-invalidation --distribution-id ${env.CLOUDFRONT_ID} --paths "/evoluwill-mfe-${{ inputs.APP_NAME }}"
