name: Build Deploy MFE Evoluwill Application
run-name: Build Deploy MFE Evoluwill Application in [${{ inputs.ENVIRONMENT }}] by ${{ github.actor }} ${{ github.run_number }}

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        description: 'Environment to run pipeline'
        required: true
        default: development
        options:
          - development
          - production
      APP_NAME:
        type: string
        description: 'Application name to deploy'
        required: true
      NODE_VERSION:
        type: choice
        description: 'Environment to run pipeline'
        required: true
        default: "16"
        options:
          - "16"
          - "18"

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  workflow:
    uses: will-bank/cxm-workflows/.github/workflows/build-deploy-mfe-evoluwill-application.yml@main
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      APP_NAME: ${{ inputs.APP_NAME }}
      NODE_VERSION: ${{ inputs.NODE_VERSION }}
    secrets: inherit
