name: Build Deploy Kubernetes Application
run-name: Build Deploy Kubernetes Application in [${{ inputs.ENVIRONMENT }}] by ${{ github.actor }} ${{ github.run_number }}

# Before running this workflow checkout its prerequisites at:
# https://github.com/will-bank/build-deploy-kubernetes-application-workflow#readme

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        description: 'Environment to run pipeline'
        required: true
        default: development
        options:
          - development
          - staging
          - production

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  workflow:
    uses: will-bank/build-deploy-kubernetes-application-workflow/.github/workflows/build-deploy-kubernetes-application.yml@v0.9.2
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      # DOCKER_BUILD_ARGS: |
      #   NPM_TOKEN
      #   BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      #   BUILD_NUMBER=${{ github.run_number }}
      #   BUILD_REF=${{ github.sha }}
    secrets: inherit
