name: Deploy Terraform

on:
  workflow_dispatch:
    # Inputs the workflow expects.
    inputs:
      ENVIRONMENT:
        type: choice
        description: 'Environment to run pipeline.'     
        required: false
        default: development
        options: 
          - development
          - staging
          - production

      WILL_PIPELINES_DEBUG:
        type: boolean
        description: 'You can check box if you want see more logs.'     
        default: false
        options: 
          - true
          - false

jobs:
  plan:
    runs-on: ubuntu-latest
    container:
      image: 142401413602.dkr.ecr.sa-east-1.amazonaws.com/will-pipelines-terraform-image:1.0.0

    steps:
      - uses: actions/checkout@v3

      - name: Terraform Plan
        run: |
          echo Here will run the plan

      - name: Terraform Apply
        run: |
          echo Here will run the apply
