name: Deploy Kubernetes Application
run-name: ${{ github.actor }} Deploy Kubernetes Application ${{ github.run_number }}
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        description: 'Environment to run pipeline'
        required: false
        default: development
        options:
          - development
          - staging
          - production

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  workflow:
    uses: will-bank/deploy-kubernetes-application-workflow/.github/workflows/deploy-kubernetes-application.yml@main     
    with:
      ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT }}
    secrets:
      PLATFORMS_TOKEN: ${{ secrets.WILLBANK_PLATFORMS_PERSONAL_ACCESS_TOKEN }}
