name: Deploy Kubernetes Application
run-name: Deploy Kubernetes Application in [${{ inputs.ENVIRONMENT }}] by ${{ github.actor }} ${{ github.run_number }}

# Before running this workflow checkout its prerequisites at:
# https://github.com/will-bank/deploy-kubernetes-application-workflow#readme

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        description: 'Environment to run pipeline'
        required: true
        default: development
        options:
          - development
          - production

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  workflow:
    uses: will-bank/deploy-kubernetes-application-workflow/.github/workflows/deploy-kubernetes-application.yml@v0.5.1
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      
    #OPTIONAL ARGS
      #FOR MONOREPO
      #DOCKERFILE_PATH: <PATH>

    secrets: inherit
