name: Deploy Terraform

on:
  workflow_dispatch:
    # Inputs the workflow expects.
    inputs:
      ENVIRONMENT:
        type: choice
        description: 'You can set this for true if you want see more logs.'     
        required: false
        default: development
        options: 
          - development
          - staging
          - production

      WILL_PIPELINES_DEBUG:
        type: boolean
        description: 'You can set this for true if you want see more logs.'     
        required: false
        default: true
        options: 
          - true
          - false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello from Octo Organization
