name: Deploy Kubernetes Application
run-name: ${{ github.actor }} Deploy Kubernetes Application ${{ github.run_number }}
on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        type: choice
        description: 'Environment to run pipeline'
        required: true
        default: development
        options:
          - development
          - staging
          - production

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  workflow:
    # See more about workflow in this doc https://github.com/will-bank/deploy-kubernetes-application-workflow#readme
    uses: will-bank/deploy-kubernetes-application-workflow/.github/workflows/deploy-kubernetes-application.yml@main     
    with:
      ENVIRONMENT: ${{ github.event.inputs.ENVIRONMENT }}
      BUILD_ENABLE: true
      BUILD_ARGS: "no"
      BUILD_PUSH_ECR: true
      KUBERNETES_MANAGER: kustomize
      KUBERNETES_UPDATE_IMAGE_TAG: true
    secrets:
      PLATFORMS_TOKEN: ${{ secrets.WILLBANK_PLATFORMS_PERSONAL_ACCESS_TOKEN }}
