# name: Deploy Terraform Application
# run-name: Deploy Terraform to ${{ inputs.ENVIRONMENT }} by ${{ github.actor }} ${{ github.run_number }}

# on:
#   workflow_dispatch:
#     inputs:
#       path:
#         description: 'Terraform Path'     
#         required: false
#         default: 'iac/terraform'
#       environment:
#         description: 'Environment' 
#         required: true
#         default: 'development'
#         type: choice
#         options:
#           - 'development'
#           - 'staging'
#           - 'production'
#       terraform_apply:
#         description: 'Terraform Apply'
#         required: true
#         default: false
#         type: boolean

# jobs:
#   workflow:
#     uses: will-bank/deploy-terraform-workflow/.github/workflows/deploy-terraform.yml@main
#     with:
#       path: ${{ inputs.path }}
#       environment: ${{ inputs.environment }}
#       terraform_apply: ${{ inputs.terraform_apply }}
#     secrets: inherit
