name: Workflow Example

on:
  workflow_dispatch:
    inputs:
      parameter:
        description: 'Parameter value'
        required: true
        type: string
        
jobs:
  reusable-workflow-call:
    uses: will-bank/test-workflow/.github/workflows/reusable_workflow.yml@v1.0.0