name: Sync Documentation PlatGPT Workflow
run-name: Sync Documentation PlatGPT Workflow in [${{ inputs.ENVIRONMENT }}] by ${{ github.actor }} ${{ github.run_number }}

# Before running this workflow checkout its prerequisites at:
# https://github.com/will-bank/sync-documentation-platgpt-workflow#readme

on:
  pull_request:

permissions:
  id-token: write
  contents: write
  actions: write

jobs:
  workflow:
    uses: will-bank/sync-documentation-platgpt-workflow/.github/workflows/sync-documentation-platgpt-workflow.yaml@v1.0.0
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
    secrets: inherit
